'use client';

import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

const BRAND: [number, number, number] = [31, 71, 245];

function header(doc: jsPDF, title: string, subtitle?: string) {
  doc.setFillColor(...BRAND);
  doc.rect(0, 0, doc.internal.pageSize.getWidth(), 22, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('CA Intern OS', 14, 10);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('One workspace for audit, reconciliation & compliance', 14, 16);
  doc.setTextColor(20, 20, 20);
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 14, 32);
  if (subtitle) {
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(90, 90, 90);
    doc.text(subtitle, 14, 38);
  }
}

function footer(doc: jsPDF, note: string) {
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    const h = doc.internal.pageSize.getHeight();
    doc.setFontSize(7.5);
    doc.setTextColor(140, 140, 140);
    doc.text(note, 14, h - 8);
    doc.text(`Page ${i} of ${pages}`, doc.internal.pageSize.getWidth() - 32, h - 8);
  }
}

export interface WpSummaryData {
  title: string;
  reference?: string | null;
  clientName: string;
  auditTitle: string;
  area: string;
  status: string;
  reviewStatus: string;
  preparedBy?: string | null;
  reviewedBy?: string | null;
  objective?: string | null;
  requiredDocuments?: string | null;
  workPerformed?: string | null;
  findings?: string | null;
  reviewerNotes?: string | null;
  checklist: { text: string; isChecked: boolean }[];
}

export function exportWorkingPaperPdf(data: WpSummaryData) {
  const doc = new jsPDF();
  header(doc, data.title, `${data.clientName} · ${data.auditTitle}`);

  autoTable(doc, {
    startY: 44,
    theme: 'plain',
    styles: { fontSize: 9, cellPadding: 1.5 },
    body: [
      ['Reference', data.reference || '—'],
      ['Audit area', data.area],
      ['Status', data.status],
      ['Review status', data.reviewStatus],
      ['Prepared by', data.preparedBy || '—'],
      ['Reviewed by', data.reviewedBy || '—'],
    ],
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 40, textColor: [90, 90, 90] } },
  });

  const sections: [string, string | null | undefined][] = [
    ['Objective', data.objective],
    ['Required documents', data.requiredDocuments],
    ['Work performed', data.workPerformed],
    ['Findings / observations', data.findings],
    ['Reviewer notes', data.reviewerNotes],
  ];

  for (const [label, value] of sections) {
    if (!value) continue;
    const y = (doc as any).lastAutoTable.finalY + 6;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(20, 20, 20);
    doc.text(label, 14, y);
    autoTable(doc, {
      startY: y + 2,
      theme: 'plain',
      styles: { fontSize: 9, cellPadding: 1, textColor: [50, 50, 50] },
      body: [[value]],
    });
  }

  if (data.checklist.length) {
    const y = (doc as any).lastAutoTable.finalY + 6;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.text('Checklist', 14, y);
    autoTable(doc, {
      startY: y + 2,
      head: [['#', 'Item', 'Done']],
      body: data.checklist.map((c, i) => [String(i + 1), c.text, c.isChecked ? 'Yes' : 'No']),
      styles: { fontSize: 9 },
      headStyles: { fillColor: BRAND },
    });
  }

  footer(
    doc,
    'Generated by CA Intern OS. Internal working paper — not a statutory certificate or professional opinion.',
  );
  doc.save(`${(data.reference || data.title).replace(/[^a-z0-9]+/gi, '-')}.pdf`);
}

export interface ReconSummaryPdf {
  title: string;
  clientName: string;
  period?: string | null;
  summary: Record<string, number>;
  generatedAt: string;
}

export function exportReconSummaryPdf(data: ReconSummaryPdf) {
  const doc = new jsPDF();
  header(doc, `GST Reconciliation — ${data.title}`, `${data.clientName}${data.period ? ` · ${data.period}` : ''}`);
  autoTable(doc, {
    startY: 44,
    head: [['Metric', 'Count']],
    body: Object.entries(data.summary).map(([k, v]) => [k, String(v)]),
    styles: { fontSize: 10 },
    headStyles: { fillColor: BRAND },
  });
  footer(
    doc,
    'Deterministic reconciliation output. Review each exception. Not a substitute for professional GST review.',
  );
  doc.save(`GST-Reconciliation-${data.title.replace(/[^a-z0-9]+/gi, '-')}.pdf`);
}
